problem: "generic_problem" # Folder name for your api.py

model:
  name: "PNN"                # Options: PNN, SIREN, FFN, etc.
  units: 128
  nz: 1                        # Number of latent/stochastic inputs
  nx: 1                        # Number of spatial inputs (x, y, t)
  ny: 1                        # Number of output fields (u, v, p)

training:
  n: 10000
  lr: 0.0001
  bz: 32                       # Batch size
  save_freq: 1000              # Iterations between checkpoints/plots
  method: "AD"                 # AD (Autograd) or FD (Finite Difference)
  seed: 42

physics:
  # Define your PDE coefficients here
  parameter_1: 0.5
  bounds: [0, 1]

data:
  path: ""